# Include shared CI
include:
    - project: "epi2melabs/ci-templates"
      file: "wf-containers.yaml"

variables:
    # Workflow inputs given to nextflow.
    # The workflow should define `--out_dir`, the CI template sets this.
    # Only common file inputs and option values need to be given here
    # (not things such as -profile)
    NF_BEFORE_SCRIPT: "wget https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-clone-validation/wf-clone-validation-db.tar.gz && tar -xzvf wf-clone-validation-db.tar.gz" 
    NF_WORKFLOW_OPTS: "--fastq test_data/test --db_directory wf-clone-validation-db --threads 4 --assm_coverage 25"
    NF_IGNORE_PROCESSES: "filterHostReads,sampleStatus"
    CI_FLAVOUR: "new"


docker-run:
    tags: [large_ram]
    parallel:
        matrix:
            - MATRIX_NAME: [
                "clone-val", "check-model"]
    rules:
        - if: ($CI_COMMIT_BRANCH == null || $CI_COMMIT_BRANCH == "dev-template")
          when: never
        - if: $MATRIX_NAME == "clone-val"
          variables:
              NF_BEFORE_SCRIPT: "wget https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-clone-validation/wf-clone-validation-db.tar.gz && tar -xzvf wf-clone-validation-db.tar.gz" 
              NF_WORKFLOW_OPTS: "--fastq test_data/test --db_directory wf-clone-validation-db \
              --threads 4 --assm_coverage 25"
              NF_IGNORE_PROCESSES: "filterHostReads,sampleStatus"
        - if: $MATRIX_NAME == "check-model"
          variables:
              NF_BEFORE_SCRIPT: "wget https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-clone-validation/wf-clone-validation-db.tar.gz && tar -xzvf wf-clone-validation-db.tar.gz" 
              NF_WORKFLOW_OPTS: "--fastq test_data/test --db_directory wf-clone-validation-db \
              --threads 4 --basecaller_cfg dna_r9.4.1_450bps_hac"
              NF_IGNORE_PROCESSES: "filterHostReads,sampleStatus"
