# Include shared CI
include:
    - project: "epi2melabs/ci-templates"
      file: "wf-containers.yaml"

variables:
    NF_BEFORE_SCRIPT: exit 0
    # Workflow inputs given to nextflow.
    # The workflow should define `--out_dir`, the CI template sets this.
    # Only common file inputs and option values need to be given here
    # (not things such as -profile)
    NF_WORKFLOW_OPTS: "--fastq test_data --host_reference test_data/GCF_000005845.2_ASM584v2_genomic.fna.gz"

