name: wf-clone-validation
channels:
    - bioconda
    - conda-forge
    - defaults
dependencies:
    - python==3.6.*
    - aplanat
    - trycycler
    - filtlong
    - porechop
    - pysam
    - minimap2
    - samtools
    - bedtools
    - mappy
    - flye
    - medaka
    - prokka