name: epi2melabs-wf-clone-validation
channels:
    - epi2melabs
    - bioconda
    - conda-forge
    - defaults
dependencies:
    - python==3.8.*
    - aplanat==0.5.7
    - seqkit
    - scikit-learn
    - trycycler
    - porechop
    - pysam
    - minimap2
    - samtools
    - bedtools
    - mappy
    - canu
    - medaka
    - fastcat==0.3.6
    - last
    - rasusa
    - pyspoa
    - epi2melabs
    - plannotate==1.2.0
