name: wf-clone-validation
channels:
    - bioconda
    - conda-forge
    - defaults
    - epi2melabs
dependencies:
    - python==3.6.*
    - aplanat
    - seqkit
    - scikit-learn
    - trycycler
    - filtlong
    - porechop
    - pysam
    - minimap2
    - samtools
    - bedtools
    - mappy
    - flye
    - medaka
    - prokka
    - fastcat
    - last